---
- hosts: head_node
  become: false
  gather_facts: true
  connection: local

  tasks:
    - name: install webserver components
      apt:
        pkg:
        - python3-pip
        - python-virtualenv
        state: present
        update_cache: yes

    - name: Install requirements
      pip:
#     ansible.builtin.pip:
        requirements: /home/ubuntu/bcm-ansible-installer/requirements-control-node.txt
        virtualenv_python: python3
        virtualenv: /home/ubuntu/bcm-ansible-installer/venv
#      collections:
#        - name: "brightcomputing.installer100"
#      pip: 
#        requirements: requirements-control-node.txt
#        virtualenv: venv

    - name: Install Bright head node
      include_role: 
        name: "brightcomputing.installer100.head_node"
#      roles:
#        - role: "brightcomputing.installer100.head_node"
