---
#- name: Install requirements
#  pip: 
#    requirements: /home/ubuntu/bcm-air-installer/requirements-control-node.txt
#    virtualenv: /home/ubuntu/bcm-air-installer/venv

- name: Install Bright head node
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  roles:
    - role: brightcomputing.installer100.localhost
