---
- hosts: head_node
  become: true
  gather_facts: true
  connection: local

  tasks:
    - name: Install requirements

      pip:
#      ansible.builtin.pip:
        requirements: requirements-control-node.txt
        virtualenv_python: python3
        virtualenv: venv
#      collections:
#        - name: "brightcomputing.installer100"
#      pip: 
#        requirements: requirements-control-node.txt
#        virtualenv: venv



    - name: Install Bright head node
      include_role: 
        name: "brightcomputing.installer100.head_node"
#      roles:
#        - role: "brightcomputing.installer100.head_node"
