---
- hosts: head_node
  become: true
  gather_facts: true
  connection: local

  tasks:
    - name: Install requirements
      collections:
        - name: brightcomputing.installer100
      pip: 
        requirements: requirements-control-node.txt
        virtualenv: venv

    - name: Install Bright head node
      roles:
        - role: brightcomputing.installer100.head_node
