---
- hosts: head_node
  become: true
  gather_facts: true
  connection: local

  tasks:
#    - name: install venv components
#      apt:
#        pkg:
#        - python3-pip
#        - python3.10-venv
#        state: present
#        update_cache: yes

    - name: Install virtualenv via pip
      pip:
        name: virtualenv
        executable: pip3
      tags:
        - venv
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.local/bin"

    - name: Install requirements
      pip:
#     ansible.builtin.pip:
        requirements: /home/ubuntu/bcm-ansible-installer/requirements-control-node.txt
        virtualenv_python: python3.10
        virtualenv: /home/ubuntu/bcm-ansible-installer/venv

    - template: src=wrapper.sh dest=/home/ubuntu/bcm-ansible-installer/venv/exec mode=755

#    collections:
#      - name: "brightcomputing.installer100"
#        type : galaxy
    - name: Install roles from Ansible Galaxy
      command: /home/ubuntu/bcm-ansible-installer/venv/exec ansible-galaxy collection install brightcomputing.installer100
#    - name: Import a brightcomputing.installer100
#      ansible.builtin.import_playbook: "brightcomputing.installer100"
#      pip: 
#        requirements: requirements-control-node.txt
#        virtualenv: venv


    - name: Install Bright head node
      include_role: 
        name: "brightcomputing.installer100.head_node"
#      roles:
#        - role: "brightcomputing.installer100.head_node"
