---
# Cluster credentials
product_key: 210015-978441-451220-980475-946141
db_cmd_password: 3tango
ldap_root_pass: 3tango
ldap_readonly_pass: 3tango
slurm_user_pass: 3tango
mysql_login_user: root
mysql_login_password: 3tango
mysql_login_unix_socket: /var/run/mysqld/mysqld.sock