---
# Cluster credentials
db_cmd_password: admin
ldap_root_pass: admin
ldap_readonly_pass: admin
slurm_user_pass: admin
mysql_login_user: root
mysql_login_password: admin
mysql_login_unix_socket: /var/run/mysqld/mysqld.sock
