---
# Cluster credentials
product_key: 168102-006594-060341-424224-650932
db_cmd_password: system
ldap_root_pass: system
ldap_readonly_pass: system
slurm_user_pass: system
mysql_login_user: root
mysql_login_password: system
mysql_login_unix_socket: /var/run/mysqld/mysqld.sock